[package]
name = "fabricgen"
description = "A quick and dirty Minecraft Fabric mod generator."
version = "0.1.0"
edition = "2021"
license = "MIT"
homepage = "https://github.com/BlueStaggo/fabricgen"
repository = "https://github.com/BlueStaggo/fabricgen"

[dependencies]
colored = "2"
